export default [
  {
    id: 1,
    name: "Wireless Mouse",
    category: "Electronics",
    price: 100,
    currency: "INR",
    inStock: true,
    rating: 4.3,
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 3499,
    currency: "INR",
    inStock: true,
    rating: 4.6,
  },
  {
    id: 3,
    name: "USB-C Hub",
    category: "Accessories",
    price: 2199,
    currency: "INR",
    inStock: false,
    rating: 4.1,
  },
  {
    id: 4,
    name: "Noise Cancelling Headphones",
    category: "Audio",
    price: 7999,
    currency: "INR",
    inStock: true,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Smart LED Bulb",
    category: "Home",
    price: 699,
    currency: "INR",
    inStock: true,
    rating: 4.0,
  },
  {
    id: 6,
    name: "Portable SSD 1TB",
    category: "Storage",
    price: 9999,
    currency: "INR",
    inStock: true,
    rating: 4.8,
  },
  {
    id: 7,
    name: "Fitness Band",
    category: "Wearables",
    price: 2499,
    currency: "INR",
    inStock: false,
    rating: 4.2,
  },
  {
    id: 8,
    name: "Laptop Stand",
    category: "Accessories",
    price: 1299,
    currency: "INR",
    inStock: true,
    rating: 4.4,
  },
  {
    id: 9,
    name: "Bluetooth Speaker",
    category: "Audio",
    price: 3199,
    currency: "INR",
    inStock: true,
    rating: 4.5,
  },
  {
    id: 10,
    name: "Webcam 1080p",
    category: "Electronics",
    price: 2899,
    currency: "INR",
    inStock: true,
    rating: 4.1,
  },
  {
    id: 11,
    name: "Desk Lamp",
    category: "Home",
    price: 1199,
    currency: "INR",
    inStock: false,
    rating: 3.9,
  },
  {
    id: 12,
    name: "Smart Watch",
    category: "Wearables",
    price: 10999,
    currency: "INR",
    inStock: true,
    rating: 4.6,
  },
  {
    id: 13,
    name: "Wireless Earbuds",
    category: "Audio",
    price: 4999,
    currency: "INR",
    inStock: true,
    rating: 4.4,
  },
  {
    id: 14,
    name: "Power Bank 20000mAh",
    category: "Accessories",
    price: 1899,
    currency: "INR",
    inStock: true,
    rating: 4.5,
  },
  {
    id: 15,
    name: "Router Dual Band",
    category: "Networking",
    price: 3599,
    currency: "INR",
    inStock: false,
    rating: 4.2,
  },
  {
    id: 16,
    name: "Office Chair",
    category: "Furniture",
    price: 8999,
    currency: "INR",
    inStock: true,
    rating: 4.3,
  },
  {
    id: 17,
    name: "Standing Desk",
    category: "Furniture",
    price: 18999,
    currency: "INR",
    inStock: false,
    rating: 4.6,
  },
  {
    id: 18,
    name: "Coffee Maker",
    category: "Kitchen",
    price: 5499,
    currency: "INR",
    inStock: true,
    rating: 4.1,
  },
  {
    id: 19,
    name: "Electric Kettle",
    category: "Kitchen",
    price: 1999,
    currency: "INR",
    inStock: true,
    rating: 4.2,
  },
  {
    id: 20,
    name: "Air Fryer",
    category: "Kitchen",
    price: 7499,
    currency: "INR",
    inStock: false,
    rating: 4.5,
  },
  {
    id: 21,
    name: "External Hard Drive 2TB",
    category: "Storage",
    price: 6499,
    currency: "INR",
    inStock: true,
    rating: 4.4,
  },
  {
    id: 22,
    name: "Graphic Tablet",
    category: "Accessories",
    price: 5799,
    currency: "INR",
    inStock: true,
    rating: 4.3,
  },
  {
    id: 23,
    name: "Action Camera",
    category: "Electronics",
    price: 12499,
    currency: "INR",
    inStock: false,
    rating: 4.5,
  },
  {
    id: 24,
    name: "Tripod Stand",
    category: "Accessories",
    price: 1599,
    currency: "INR",
    inStock: true,
    rating: 4.0,
  },
  {
    id: 25,
    name: "Smart Plug",
    category: "Home",
    price: 999,
    currency: "INR",
    inStock: true,
    rating: 4.1,
  },
];
